---
deployment:
  tasks:
    - export DEPLOYPATH=/home/starbycc/public_html # Change 'starbycc' to your cPanel username
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R /home/starbycc/repositories/StarBikePanel/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - npm install --prefix $DEPLOYPATH
    - npm run build --prefix $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/node_modules
    - /bin/rm -f $DEPLOYPATH/package-lock.json
    - /bin/rm -f $DEPLOYPATH/.gitignore
    - /bin/cp /home/starbycc/repositories/StarBikePanel/.env $DEPLOYPATH/.env # Copy .env file
