---
deployment:
  tasks:
    - /bin/rm -rf /home/starbycc/public_html/*
    - /bin/cp -R /home/starbycc/repositories/StarBikePanel/* /home/starbycc/public_html
    - npm install -f --prefix /home/starbycc/public_html
    - npm run build --prefix /home/starbycc/public_html
